"""initial tables

Revision ID: 0a803b2c6d4d
Revises: 
Create Date: 2026-05-08 12:31:09.719059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a803b2c6d4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('projectName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('projectName')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('references',
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_references_ref_id'), 'references', ['ref_id'], unique=False)
    op.create_table('inspections',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=False),
    sa.Column('done_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['done_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ref_id'], ['references.ref_id'], ),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    op.create_index(op.f('ix_inspections_inspection_id'), 'inspections', ['inspection_id'], unique=False)
    op.create_table('reference_data',
    sa.Column('slotId', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('identification_id', sa.String(), nullable=False),
    sa.Column('amperage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ref_id'], ['references.ref_id'], ),
    sa.PrimaryKeyConstraint('slotId')
    )
    op.create_index(op.f('ix_reference_data_slotId'), 'reference_data', ['slotId'], unique=False)
    op.create_table('errors',
    sa.Column('slotId', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('extracted_id', sa.String(), nullable=True),
    sa.Column('expected_id', sa.String(), nullable=False),
    sa.Column('extracted_amp', sa.String(), nullable=True),
    sa.Column('expected_amp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.inspection_id'], ),
    sa.PrimaryKeyConstraint('slotId', 'inspection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('errors')
    op.drop_index(op.f('ix_reference_data_slotId'), table_name='reference_data')
    op.drop_table('reference_data')
    op.drop_index(op.f('ix_inspections_inspection_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_references_ref_id'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
