"""change reference_data primary key to composite

Revision ID: 28a83d8f31bd
Revises: da2888264bdc
Create Date: 2026-05-13 11:52:25.108400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a83d8f31bd'
down_revision: Union[str, Sequence[str], None] = 'da2888264bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('errors', 'slotId',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('inspections', 'ref_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('reference_data_pkey', 'reference_data', type_='primary')
    op.create_primary_key(
        'reference_data_pkey',
        'reference_data',
        ['slotId', 'ref_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspections', 'ref_id',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('errors', 'slotId',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
