"""add is_archived to references

Revision ID: 3b0e9d974966
Revises: 28a83d8f31bd
Create Date: 2026-05-22 15:13:07.768021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0e9d974966'
down_revision: Union[str, Sequence[str], None] = '28a83d8f31bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('is_archived', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'is_archived')
    # ### end Alembic commands ###
