"""add bbox to errors

Revision ID: 42a47041a65d
Revises: 3b0e9d974966
Create Date: 2026-05-25 15:19:51.229376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42a47041a65d'
down_revision: Union[str, Sequence[str], None] = '3b0e9d974966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errors', sa.Column('where', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('errors', sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('errors', 'bbox')
    op.drop_column('errors', 'where')
    # ### end Alembic commands ###
